allowBuilds:
  core-js: true
minimumReleaseAgeExclude:
  - js-yaml@4.1.2
overrides:
  js-yaml@<=4.1.1: ^4.1.2
  serialize-javascript@<7.0.5: ^7.0.5
  serialize-javascript@<=7.0.2: ^7.0.3
  sirv@<3.0.2: ^3.0.2
  uuid@<14.0.0: ^14.0.0
